defaults: &defaults
  docker:
    - image: cimg/node:14.15.1

version: 2.1

jobs:
  unit_tests:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ .Branch }}-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - cache-
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
      - run:
          command: yarn test
          environment:
            JEST_JUNIT_OUTPUT: "test-reports/jest-junit.xml"
      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports
  deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: deploy-site
          command: curl -X POST -d {} $DEPLOY_SITE

workflows:
  version: 2
  ut_and_build:
    jobs:
      - unit_tests
      - deploy:
          requires:
            - unit_tests
          filters:
            branches:
              only: main
